# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2b4c9d56a3f3f61458d3c845e57813c3e350454c608a4eb7ac91b0c68e203b7505efa93489f1dfb58753fec731914e669b9348af168efd48eb9355cd119e888

test:
  secret_key_base: 354e29eaa8690812afc4cb13a74519792428c23ba9cf7b796b74a2164f1078ad030d4c7f5584c0a11a7e9f5d772bdf3a91779e5b1c2f8a39085861179536aee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
